# Generated by Django 5.0.7 on 2024-07-29 13:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('user_type', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('user_type', models.CharField(default='worker', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Land_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqrtft', models.CharField(max_length=50)),
                ('type_land', models.CharField(max_length=200)),
                ('cultivation', models.CharField(max_length=50)),
                ('acres', models.CharField(max_length=100)),
                ('soil', models.CharField(max_length=100)),
                ('pipes', models.CharField(max_length=100)),
                ('sale', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('about_land', models.TextField(max_length=1000)),
                ('place', models.TextField(max_length=1000)),
                ('status', models.CharField(max_length=30)),
                ('saled_price', models.CharField(max_length=100)),
                ('posted_date', models.DateField(default=datetime.datetime(2024, 7, 29, 13, 9, 51, 955602, tzinfo=datetime.timezone.utc))),
                ('video', models.FileField(null=True, upload_to='documents/', verbose_name='Upload Video')),
                ('image', models.FileField(null=True, upload_to='documents/', verbose_name='Upload Image')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Sale_Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateField(default=datetime.datetime(2024, 7, 29, 13, 9, 51, 956601, tzinfo=datetime.timezone.utc))),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register_detail')),
                ('land_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.land_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(max_length=2000)),
                ('price', models.FloatField(max_length=100)),
                ('tractor_image', models.FileField(null=True, upload_to='documents/', verbose_name='Upload Image')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=50)),
                ('interview_date', models.DateField()),
                ('desc', models.TextField(max_length=1000)),
                ('place', models.TextField(max_length=1000)),
                ('posted_date', models.DateField(default=datetime.datetime(2024, 7, 29, 13, 9, 51, 954601, tzinfo=datetime.timezone.utc))),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.worker_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=200)),
                ('farmer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.register_detail')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.worker_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('job_status', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=50)),
                ('farmer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.register_detail')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.worker_detail')),
            ],
        ),
    ]
