# Generated by Django 5.0.7 on 2024-08-01 12:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_job_detail_posted_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.job_detail'),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='posted_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 1, 12, 30, 40, 506059, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='land_detail',
            name='posted_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 1, 12, 30, 40, 507059, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sale_land',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 1, 12, 30, 40, 508059, tzinfo=datetime.timezone.utc)),
        ),
    ]
