# Generated by Django 5.0.7 on 2024-08-01 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_apply_job_id_alter_job_detail_posted_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_detail',
            name='posted_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 1, 12, 30, 54, 630419, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='land_detail',
            name='posted_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 1, 12, 30, 54, 631419, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sale_land',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 1, 12, 30, 54, 632419, tzinfo=datetime.timezone.utc)),
        ),
    ]
