# Generated by Django 5.0.7 on 2025-01-23 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_job_detail_posted_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_detail',
            name='posted_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 23, 6, 6, 0, 34621, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='land_detail',
            name='posted_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 23, 6, 6, 0, 35620, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sale_land',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 23, 6, 6, 0, 35620, tzinfo=datetime.timezone.utc)),
        ),
    ]
